# Generated by Django 5.2.12 on 2026-08-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0008_invite_for_telegram_user_id'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='invites.telegramprofile')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='wishlists.wish')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('wish', 'profile'), name='unique_reservation')],
            },
        ),
    ]
