# Generated by Django 5.2.12 on 2026-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0008_invite_for_telegram_user_id'),
        ('wishlists', '0002_wishreservation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishreservation',
            name='unique_reservation',
        ),
        migrations.AddConstraint(
            model_name='wishreservation',
            constraint=models.UniqueConstraint(fields=('wish',), name='unique_reservation'),
        ),
    ]
