# Generated by Django 5.2.12 on 2026-08-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_remove_wishreservation_unique_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
    ]
