# Generated by Django 5.2.12 on 2026-08-04 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0008_invite_for_telegram_user_id'),
        ('wishlists', '0004_wish_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invites.telegramprofile')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='wishlists.wishlist')),
            ],
        ),
    ]
