# Generated by Django 5.2.12 on 2026-08-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0008_invite_for_telegram_user_id'),
        ('wishlists', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_accesses', to='invites.telegramprofile')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_accesses', to='wishlists.wishlist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'wishlist'), name='unique_wishlist_access')],
            },
        ),
    ]
