# Generated by Django 5.2.12 on 2026-08-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0008_invite_for_telegram_user_id'),
        ('wishlists', '0006_wishlistaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_accesses', to='wishlists.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_accesses', to='invites.telegramprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'event'), name='unique_event_access')],
            },
        ),
    ]
