# Generated by Django 5.2.12 on 2026-08-16 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0008_invite_for_telegram_user_id'),
        ('wishlists', '0007_eventaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('occurs_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_plan', to='invites.telegramprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GiftPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='wishlists.giftplan')),
                ('wish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='wishlists.wish')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('wish__isnull', False), models.Q(('title__isnull', False), ('url__isnull', False)), _connector='OR'), name='xor_gift_plan_item')],
            },
        ),
    ]
