# Generated by Django 5.2.12 on 2026-08-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0008_giftplan_giftplanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='preview_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wish',
            name='preview_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
