# Generated by Django 5.2.12 on 2026-08-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0009_wish_preview_image_url_wish_preview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishreservation',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
