# Generated by Django 5.2.12 on 2026-08-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0011_alter_wishreservation_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishreservation',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
