# Generated by Django 5.2.12 on 2026-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000, unique=True, verbose_name='Токен')),
                ('max_uses', models.IntegerField(default=0, verbose_name='Разрешонное кол-во активаций')),
                ('used_count', models.IntegerField(default=0, verbose_name='Кол-во активаций')),
                ('expires_at', models.DateTimeField(null=True, verbose_name='Срок действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
