# Generated by Django 5.2.12 on 2026-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='max_uses',
            field=models.IntegerField(default=1, verbose_name='Разрешонное кол-во активаций'),
        ),
    ]
