# Generated by Django 5.2.12 on 2026-04-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_alter_invite_max_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия'),
        ),
    ]
