# Generated by Django 5.2.12 on 2026-04-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0004_telegramprofile_alter_invite_max_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_user_id',
            field=models.IntegerField(unique=True, verbose_name='Id Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Никнейм'),
        ),
        migrations.CreateModel(
            name='InviteActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField()),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invites.invite')),
                ('telegram_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invites.telegramprofile')),
            ],
        ),
    ]
