# Generated by Django 5.2.12 on 2026-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0005_alter_telegramprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_user_id',
            field=models.BigIntegerField(unique=True, verbose_name='Id Telegram'),
        ),
    ]
