# Generated by Django 5.2.12 on 2026-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0006_alter_telegramprofile_telegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteactivation',
            name='activated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='inviteactivation',
            unique_together={('invite', 'telegram_profile')},
        ),
    ]
